### ISSUE TITLE
Dependency Graph

### ISSUE THREAD

**Issue by michaelpfohl** [nss-evening-cohort-13/pants-group-project-todo-team-name-team-2#25]
## Tickets WITH Dependencies
Tickets are listed in the order they need to be developed. DO NOT start a ticket before ensuring the ticket before it is completed.
 - [x] HTML - All Pages - Footer - (@michaelpfohl ) - #4
 - [x]  HTML - All Pages - Jumbotron & Navbar - (@Jonathon22 ) - #5
 - [x] HTML - Home Page - Main Image - (@HunterJuneau) - #6
 - [x] JS - Product Page - Build Product Cards - (@michaelpfohl) - #9
 - [x] JS - Product Page - Add to Cart - (@michaelpfohl) - #10
 - [x]  JS - Product Page - Add to Wishlist - (@michaelpfohl) - #11
- [X] JS - Product Page - Display Number of Items in Cart in Navbar - (@michaelpfohl) - #34 
- [X] HTML & JS - Product Page - Display Wishlist in Navbar and Number of Items in Wishlist - (@michaelpfohl) - #37
 - [x] JS - Product Page - Size Dropdown - (@michaelpfohl) - #12
 - [x] JS - Product Page - Filter Products by Type - (@michaelpfohl) - #43 
 - [x] HTML and JS - Home Page - Feature Cards (@HunterJuneau ) - #16
 - [x]  HTML and JS - Home Page - Featured Products (@HunterJuneau) - #19
 - [ ] HTML- About Page(@Jonathon22 ) - #8
 - [ ] HTML and JS - About Page - vertical nav of history, learn more, and news (@Jonathon22 ) - #14
 - [ ] HTML and JS - About Page - Comments Form (@Jonathon22 ) - #17
 - [x]  JS - Cart Page - Cart Products (@liz-barnes) - #15 
 - [ ]  JS - Cart Page - Remove from Cart (@liz-barnes) - #20
 - [ ]  JS - Cart Page - Wishlist (@liz-barnes) - #21 
 - [ ]  JS - Cart Page - Add to Cart (@liz-barnes) - #23 
 - [ ]  JS - Cart Page - Remove from Wishlist (@liz-barnes) - #22 
 - [ ]  JS - Cart Page - Order Summary (@liz-barnes) - #13 
 - [ ]  JS - Cart Page - Checkout Button & Form (@liz-barnes) - #18 
 - [ ] HTML and JS - Home Page - Reviews (@HunterJuneau) - #47 

 ## Tickets WITHOUT Dependencies
  - [x] setup initial file - (@michaelpfohl ) - #3
  - [ ] Figma - Logo Design - (@liz-barnes) - #24
